# Generated by Django 2.2 on 2023-01-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
