# Generated by Django 2.2 on 2023-01-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0009_auto_20230108_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
