# Generated by Django 2.2 on 2023-01-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0010_auto_20230108_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
